### PR TITLE
Fix double scheme output if set in site domain

### LINKED ISSUE #62: Sitemap URL with double scheme
I have a setup of Django CMS + Gunicorn + Nginx and when the robots.txt file is displayed, it shows the scheme of the URL twice.

This is the robots file that is generated:

User-agent: *
Allow: /
Disallow: /admin

Host: https://www.chitwa.co.za
**Sitemap: https://https://www.chitwa.co.za/en/sitemap.xml**

### LINKED ISSUE #64: Swappable site model
Hi,

As stated in issue #63 adding support for wagtail isn't in scope of this package, I agree on that.. I was wondering if it's feasible to have the site model via a setting (just like django's swappable User model). That way we can easily integrate with whatever package which uses a different model for its Sites.

Hope you'll agree on this? If so, we can provide a PR for this..

### PR DESCRIPTION
**Pull request by yakky**
Fix #62

### CODE REVIEW

**Comment by yakky** [comment]
@tyapkov would you tests if this PR fixes your issues with #62 ?

**Comment by tyapkov** [comment]
@yakky update solves the problem, but now sitemap record in robots.txt is now always shown with protocol.

**Comment by yakky** [comment]
@tyapkov is this comment still true after https://github.com/jazzband/django-robots/issues/62#issuecomment-279635313?

**Comment by yakky** [comment]
I anyway rebased it on top of the current master which also includes the fix to detect the correct request protocol

**Pull request merged**
