### PR TITLE
Fix typo in RuleAdminForm validation error message

### PR DESCRIPTION
**Pull request by apoorvaeternity**

### CODE REVIEW

**Comment by tony** [comment]
I overlooked this PR - I apologize.

This same change was swept in https://github.com/jazzband/django-robots/commit/e9833414d081f622e3b969d3c68e96cbc2c925f2 when I ran [`typos`](https://github.com/crate-ci/typos) on the codebase.

Fine if I still give you credit in the CHANGELOG? Even if the changeset isn't in the git history itself?

Again, my mistake.

**Comment by tony** [comment]
@apoorvaeternity Directly mentioning you also, in regards to [the above comment](https://github.com/jazzband/django-robots/pull/145#issuecomment-1710063300).

**Comment by apoorvaeternity** [comment]
`Fine if I still give you credit in the CHANGELOG?` - @tony that's completely fine :)

**Comment by tony** [comment]
@apoorvaeternity How is this?

- 7e90577
- Release updated: https://github.com/jazzband/django-robots/releases/tag/6.1
- [CHANGES.rst](https://github.com/jazzband/django-robots/blob/7e90577/CHANGES.rst#:~:text=typos%20via%20typos-,Special%20thanks,-to%20typo%20fix)

**Comment by apoorvaeternity** [comment]
@tony it's perfect. Closing this PR now.

**Comment by tony** [comment]
Hooray!  Good this worked out!

**Pull request closed without merging**
