### PR TITLE
Detect current site via http host var

### PR DESCRIPTION
**Pull request by dborisov**
Hi guys,

In addition to default Django's site detection by SITE_ID from settings.py I want to add support of dynamic site detection mechanism. It is very usefull when you does not have separate settings.py per-site but want to serve multiple sites on single Django instance. In my case it is Mezzanine CMS which has native multisite without per-site settings support and I want to run django-robots same way.
This solution is not Mezzanine specific, it is pretty universal.
Lets try to merge it =)

### CODE REVIEW

**Comment by dborisov** [comment]
I'm very sorry, I'd never use Travis. Where I can find correct .travis.yml and how can update the pull request?

**Comment by yakky** [comment]
@dborisov currently there are no test for django-robots, so disregard the above failure

**Comment by yakky** [comment]
@dborisov thanks, LGTM, merging this

**Comment by ogonkov** [comment]
Docs misisng

**Pull request merged**
