### PR TITLE
Url patterns marked as safe in template

### PR DESCRIPTION
**Pull request by pierreben**
Hi, 

Thanks for all the work you've done on django-robots.
I suggest to mark the urlpatterns as safe in template to allow patterns including chars like &.

#### Before:
```
User-agent: *
Allow: /bar/?foo=1&amp;foobar=2
Disallow: /bar/?foo=1&amp;foobar=2
```

#### After: 
```
User-agent: *
Allow: /bar/?foo=1&foobar=2
Disallow: /bar/?foo=1&foobar=2
```

### CODE REVIEW

**Comment by auvipy** [comment]
plz do fix the conflict :)

**Comment by yakky** [comment]
@pierreben do you mind to fix the conflict?

**Comment by yakky** [comment]
@pierreben awaesome!

**Comment by yakky** [comment]
@pierreben thanks for your contribution. merging this

**Comment by pierreben** [comment]
You're welcome, it was my pleasure.

**Pull request merged**
